### ISSUE TITLE
Seems like System colours do not work.

### ISSUE THREAD

**Issue by vincentneo** [intitni/SmoothGradient#4]
Tried this out with `Color` init'd with `UIColor`'s `.systemRed` and `.systemGreen`, seems to not work, as array returned were all `.clear`.

**Comment by intitni** [comment]
The `Color`'s `cgColor` was nil when created from dynamic colors which I used to get its RGBA values. Now I convert it back into `NSColor` or `UIColor` instead if possible.

Released in 0.3.1
